'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Loader2,Send,Plug,ChevronDown} from 'lucide-react';

type Props={obraId:string;breadcrumbItems:{id:string|null;title:string}[];selectedIds:string[];onClearSelection:()=>void;onCanvasMaybeChanged:()=>void;defaultOpen?:boolean};
type ModelOption={id:string;label:string;description:string};
type Capability={id:'local'|'openai'|'claude'|'cursor';label:string;models:ModelOption[];limitDescription:string};
type Usage={provider?:string;model?:string;inputTokens?:number;outputTokens?:number;cachedInputTokens?:number;durationMs?:number;local?:boolean;limitDescription?:string};
type Job={id:string;prompt:string;status:string;result?:{reply:string;operations:Record<string,unknown>[]};error?:string;created_at:string;context?:{provider?:string;model?:string};usage?:Usage;activity?:string};
type Device={id:string;last_seen_at:string|null;capabilities?:Capability[];usage?:Usage;activity?:string};
const LOCAL:Capability={id:'local',label:'Automático local',models:[{id:'automatico',label:'Sin IA cuando sea posible',description:'Usa reglas locales primero y Codex solo si hace falta.'}],limitDescription:'Las operaciones locales no consumen suscripción.'};
const statusLabel:Record<string,string>={queued:'Pendiente · esperando a tu PC',running:'Tu agente está trabajando',completed:'Propuesta lista para revisar',failed:'No se pudo completar',cancelled:'Cancelado',applied:'Cambios aceptados'};
export function GrowsCommandBar({obraId,breadcrumbItems,selectedIds,onClearSelection,onCanvasMaybeChanged,defaultOpen}:Props){
 const [open,setOpen]=useState(!!defaultOpen),[draft,setDraft]=useState(''),[jobs,setJobs]=useState<Job[]>([]),[devices,setDevices]=useState<Device[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[pairToken,setPairToken]=useState<string|null>(null),[settings,setSettings]=useState(false);
 const [provider,setProvider]=useState('local'),[model,setModel]=useState('automatico');
 const [legacy,setLegacy]=useState<{id:string;role:string;text:string}[]>([]);
 const end=useRef<HTMLDivElement>(null);
 const endpoint=`/api/obras/${encodeURIComponent(obraId)}/bridge`;
 const load=useCallback(async()=>{try{const res=await fetch(endpoint,{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.message);setJobs(data.jobs??[]);setDevices(data.devices??[]);}catch(e){setError(e instanceof Error?e.message:'No se pudo leer el puente.');}},[endpoint]);
 useEffect(()=>{setJobs([]);setDevices([]);setLegacy([]);setDraft('');setPairToken(null);setError(null);void fetch(`/api/obras/${encodeURIComponent(obraId)}/canvas`,{cache:'no-store'}).then(r=>r.json()).then(j=>setLegacy(j.data?.obra?.canvas_ui?.hilo??[])).catch(()=>{});},[obraId]);
 useEffect(()=>{if(!open)return;void load();const timer=setInterval(()=>void load(),4000);return()=>clearInterval(timer);},[open,load]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setOpen(o=>!o);}if(e.key==='Escape')setOpen(false);};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
 useEffect(()=>end.current?.scrollIntoView({block:'nearest'}),[jobs.length]);
 const send=async(action:string,extra:Record<string,unknown>={})=>{setBusy(true);setError(null);try{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...extra})});const data=await res.json();if(!res.ok)throw new Error(data.message);if(data.token)setPairToken(data.token);if(action==='enqueue')setDraft('');if(action==='apply')onCanvasMaybeChanged();await load();return data;}catch(e){setError(e instanceof Error?e.message:'No se pudo completar.');}finally{setBusy(false);}};
 const connected=devices.some(d=>d.last_seen_at&&Date.now()-Date.parse(d.last_seen_at)<30000);
 const capabilities=useMemo(()=>{
  const current=devices.filter(d=>d.last_seen_at&&Date.now()-Date.parse(d.last_seen_at)<30000).flatMap(d=>d.capabilities??[]);
  const unique=new Map<string,Capability>();for(const item of current)unique.set(item.id,item);
  return [LOCAL,...unique.values()];
 },[devices]);
 const selectedCapability=capabilities.find(c=>c.id===provider)??capabilities[0];
 const models=selectedCapability?.models??[];
 const selectedModel=models.find(item=>item.id===model)??models[0];
 useEffect(()=>{if(!models.some(item=>item.id===model))setModel(models[0]?.id??'automatico');},[provider,model,models]);
 const download=()=>{if(!pairToken)return;const config=JSON.stringify({url:window.location.origin,token:pairToken},null,2);const url=URL.createObjectURL(new Blob([config],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='grows-bridge.private.json';a.click();URL.revokeObjectURL(url);};
 return <div className="absolute bottom-4 left-1/2 z-40 w-[min(680px,calc(100%-112px))] -translate-x-1/2">
 {open&&<section aria-label="Conversación de la obra" className="mb-2 flex max-h-[65dvh] flex-col overflow-hidden rounded-xl border border-stone-300 bg-white shadow-xl">
  <header className="flex items-center justify-between border-b px-4 py-3"><div><strong className="text-sm">Grows · tu espacio de trabajo</strong><p className="text-xs text-stone-500">{connected?'PC conectada · elegí proveedor y modelo':'PC desconectada · tus pedidos quedan pendientes'}</p>{devices.find(d=>d.activity)?.activity&&<p className="mt-1 text-xs text-blue-700">{devices.find(d=>d.activity)?.activity}</p>}</div><div className="flex gap-3"><button aria-label="Conectar PC" onClick={()=>setSettings(s=>!s)}><Plug size={17}/></button><button aria-label="Colapsar chat" onClick={()=>setOpen(false)}><ChevronDown size={17}/></button></div></header>
  {settings&&<div className="space-y-2 border-b bg-stone-50 p-4 text-xs"><p>Conectá tu PC para trabajar con el agente de tu suscripción. La aplicación conserva los pedidos y muestra los cambios antes de aplicarlos.</p><button disabled={busy} className="rounded border bg-white px-3 py-2" onClick={()=>void send('pair')}>Emparejar esta obra</button>{pairToken&&<div><p>Descargá la conexión privada y abrila con el puente local. No la compartas.</p><button onClick={download} className="mt-2 rounded bg-slate-900 px-3 py-2 text-white">Descargar conexión</button></div>}{devices.map((d,i)=><div key={d.id} className="flex justify-between"><span>PC {i+1} · {d.last_seen_at?'conectada anteriormente':'pendiente de conectar'}</span><button disabled={busy} onClick={()=>void send('revoke',{deviceId:d.id})}>Desconectar</button></div>)}</div>}
  <div className="min-h-20 flex-1 space-y-4 overflow-auto p-4 text-sm">
   {legacy.map(m=><div key={m.id}><span className="text-xs text-stone-400">{m.role==='user'?'Vos':'Grows · conversación anterior'}</span><p className="whitespace-pre-wrap">{m.text}</p></div>)}
   {!jobs.length&&!legacy.length&&<p className="text-stone-500">Pedile a Grows que organice los cuadros, revise dependencias o proponga un trabajo. Seleccioná cuadros para indicar dónde trabajar.</p>}
   {[...jobs].reverse().map(job=>{const measured=!!(job.usage?.inputTokens||job.usage?.outputTokens);return <article key={job.id} className="space-y-2 border-b pb-4"><p className="font-medium">{job.prompt}</p><p className="text-xs text-stone-500">{statusLabel[job.status]??job.status} · {job.context?.provider==='local'?'Automático local':job.context?.provider??'OpenAI'} · {job.context?.model??'automático'}</p>{job.activity&&job.status==='running'&&<p className="rounded bg-blue-50 px-2 py-1 text-xs text-blue-800">{job.activity}</p>}{job.usage&&<p className="text-xs text-stone-500">{job.usage.local?'Sin consumo de IA':measured?`${(job.usage.inputTokens??0).toLocaleString()} entrada · ${(job.usage.outputTokens??0).toLocaleString()} salida`:'El proveedor no informó tokens'}{job.usage.durationMs?` · ${Math.round(job.usage.durationMs/1000)} s`:''}</p>}{job.result&&<><p className="whitespace-pre-wrap">{job.result.reply}</p>{job.result.operations.length>0&&<details><summary className="cursor-pointer text-xs">Revisar {job.result.operations.length} cambios</summary><ol className="mt-2 space-y-1 text-xs">{job.result.operations.map((op,i)=><li key={i}>{i+1}. {String(op.type)} · {String(op.title??op.id??op.sourceId??'Relación')}<pre className="whitespace-pre-wrap break-words text-stone-500">{JSON.stringify(op,null,2)}</pre></li>)}</ol></details>}</>}{job.error&&<p className="text-red-700">{job.error}</p>}{job.status==='completed'&&!!job.result?.operations.length&&<button disabled={busy} onClick={()=>void send('apply',{jobId:job.id})} className="rounded bg-slate-900 px-3 py-2 text-xs text-white">Aceptar cambios</button>}{['queued','running','completed'].includes(job.status)&&<button disabled={busy} onClick={()=>void send('cancel',{jobId:job.id})} className="ml-3 text-xs text-stone-600">{job.status==='completed'?'Descartar':'Cancelar'}</button>}</article>})}<div ref={end}/>
  </div>
 </section>}
 <form onSubmit={e=>{e.preventDefault();if(!draft.trim()||busy)return;setOpen(true);void send('enqueue',{prompt:draft.trim(),provider,model,scopePathIds:breadcrumbItems.map(b=>b.id).filter(Boolean),selectionIds:selectedIds});}} className="rounded-xl border border-stone-300 bg-white p-3 shadow-lg">
  <div className="mb-1 flex justify-between text-[11px] text-stone-500"><button type="button" onClick={()=>setOpen(o=>!o)}>{breadcrumbItems.map(b=>b.title).join(' › ')} · {open?'Cerrar conversación':'Abrir conversación'}</button>{selectedIds.length>0&&<button type="button" onClick={onClearSelection}>{selectedIds.length} seleccionados ×</button>}</div>
  <div className="mb-2 flex gap-2"><select aria-label="Proveedor" value={provider} onChange={e=>setProvider(e.target.value)} className="rounded border bg-stone-50 px-2 py-1 text-xs">{capabilities.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select><select aria-label="Modelo" value={selectedModel?.id??model} onChange={e=>setModel(e.target.value)} className="min-w-40 flex-1 rounded border bg-stone-50 px-2 py-1 text-xs">{models.map(item=><option key={item.id} value={item.id}>{item.label} · {item.description}</option>)}</select></div>
  <p className="mb-2 text-[10px] text-stone-500">{selectedModel?.description} {selectedCapability?.limitDescription}</p>
  <div className="flex items-end gap-3"><textarea aria-label="Pedido a Grows" value={draft} onFocus={()=>setOpen(true)} onChange={e=>setDraft(e.target.value)} placeholder="Preguntale o pedile algo a Grows…" maxLength={8000} rows={1} className="min-h-9 flex-1 resize-none bg-transparent text-sm outline-none" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit();}}}/><button disabled={busy||!draft.trim()} aria-label="Enviar pedido" className="rounded-lg bg-slate-900 p-2 text-white disabled:opacity-40">{busy?<Loader2 className="animate-spin" size={17}/>:<Send size={17}/>}</button></div>
  {error&&<p role="alert" className="mt-2 text-xs text-red-700">{error}</p>}
 </form></div>;
}
